allowBuilds:
  '@nestjs/core': false
  '@parcel/watcher': false
  '@swc/core': false
  argon2: false
  esbuild: false
  less: false
  lmdb: false
  msgpackr-extract: false
  nx: false
  unrs-resolver: false
